spring.application.name=Bakery

# ???????? ???? ???????? ????:
spring.datasource.url=jdbc:mysql://localhost:3306/cake_house_db
spring.datasource.username=root
spring.datasource.password=19102005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?????????? Spring ?????????? ??????? (User, Role ????) ????????? ???? ????:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

openai.api.key=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