spring.application.name=Bakery

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cake_house_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:19102005}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

# ???????: ????? ??????? ?????? ??? ???????????? ????
# ??? ????? Spring ???????? ????? ?????? 1MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

openai.api.key=${OPENAI_API_KEY}


app.base-url=${APP_BASE_URL:http://localhost:8080}
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_USERNAME:noreply@bakery.com}
